import { SelectOption } from '@/components/Elements/Select'

export enum Units {
  None = '',
  Meter = 'm',
  Millimeter = 'mm',
  Centimeter = 'cm',
  Decimeter = 'dm',
  Kilometer = 'km',
  Squaremeter = 'qm',
  Squarekilometer = 'qkm',
  Cubicmeter = 'm³',
  Litre = 'l',
  Millilitre = 'ml',
  Centilitre = 'cl',
  Decilitre = 'dl',
  Hectolitre = 'hl',
  Kilogram = 'kg',
  Milligram = 'mg',
  Gram = 'g',
  Pound = 'lb',
  Radian = 'rad',
  Degree = '°',
  Second = 's',
  Minute = 'min',
  Hour = 'h',
  Day = 'd',
  Percent = '%',
}

/*
export const unitOptions: SelectOption[] [
  { value: ''},
  { value: 'm'},
  { value: 'mm'},
  { value: 'cm'},
  { value: 'dm'},
  { value: 'km'},
  { value: 'qm'},
  { value: 'qkm'},
  { value: 'm³'},
  { value: 'l'},
  { value:'ml'},
  { value: 'cl'},
  { value: 'dl'},
  { value: 'hl'},
  { value: 'kg'},
  { value: 'mg'},
  { value: 'g'},
  { value: 'lb'},
  { value: 'rad'},
  { value: '°'},
  { value: 's'},
  { value: 'min'},
  { value: 'h'},
  { value: 'd'},
  { value: '%'},
]*/
