export enum Units {
  None = '',
  Meter = 'm',
  Millimeter = 'mm',
  Centimeter = 'cm',
  Decimeter = 'dm',
  Kilometer = 'km',
  Squaremeter = 'qm',
  Squarekilometer = 'qkm',
  Cubicmeter = 'm³',
  Litre = 'l',
  Millilitre = 'ml',
  Centilitre = 'cl',
  Decilitre = 'dl',
  Hectolitre = 'hl',
  Kilogram = 'kg',
  Milligram = 'mg',
  Gram = 'g',
  Pound = 'lb',
  Radian = 'rad',
  Degree = '°',
  Second = 's',
  Minute = 'min',
  Hour = 'h',
  Day = 'd',
  Percent = '%',
}
